# Generated by Django 4.2.3 on 2024-08-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirdFluData',
        ),
    ]
